#!/usr/bin/env python3
"""Render every LaTeX table in the paper from the persisted result artifacts.

Single source of truth: nothing in `facct27_digital_eyes_on_the_street/tables/` is
hand-edited. Each table is generated here from `data/derived/results/*.json` (written by
the Rust batch + the analysis scripts) or `data/derived/exposure/*.csv`, so a re-bake
propagates to the paper by re-running this file and recompiling. If a number in the paper
cannot be traced to a file this script reads, it does not belong in the paper.

    uv run python tools/make_tables.py            # write tables/*.tex
    uv run python tools/make_tables.py --check    # exit 1 if any table is stale

Every table also emits a `% generated by tools/make_tables.py from <source>` provenance
comment, so a reader of the .tex can find the artifact it came from.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESULTS = ROOT / "data/derived/results"
EXPOSURE = ROOT / "data/derived/exposure"
TABLES = ROOT / "facct27_digital_eyes_on_the_street/tables"

# Column order for anything reported by focal covariate. Keep it fixed across tables so a
# reader can scan down the paper without re-learning the layout.
FOCALS = [("%Hisp", r"\%Hispanic"), ("%Black", r"\%Black"), ("%White", r"\%White"), ("income", "Median income")]


def load_json(name: str) -> dict:
    p = RESULTS / f"{name}.json"
    if not p.exists():
        sys.exit(f"missing {p}. Run the analysis scripts first (see {RESULTS}/README.md).")
    return json.loads(p.read_text())


def se(x: float) -> str:
    return f"{x:.2f}"


def signed(x: float, nd: int = 2) -> str:
    """Explicit sign on every coefficient, in math mode.

    A table of disparities is a table of signs, so the sign must be legible: in text mode LaTeX
    renders ``-'' as a hyphen, which is visibly shorter than a minus and sits at the wrong height.
    """
    return f"${x:+.{nd}f}$"


def wrap(
    body: str,
    *,
    caption: str,
    label: str,
    colspec: str,
    note: str = "",
    source: str = "",
    wide: bool = True,
) -> str:
    """Emit one booktabs table.

    `wide` selects `table*` (spans both columns of the ACM two-column layout). Most of these
    tables have five or more numeric columns and will not fit a 3.3in column, so it defaults on.

    The note goes inside a `minipage`, not loose after the `tabular`: `\\centering` is still in
    force at that point, so an unboxed paragraph gets its first line centred and then flows past
    the table's right edge.
    """
    env = "table*" if wide else "table"
    note_tex = (
        f"\n  \\vspace{{3pt}}\n"
        f"  \\begin{{minipage}}{{\\linewidth}}\n"
        f"    \\footnotesize\\raggedright {note}\n"
        f"  \\end{{minipage}}\n"
        if note
        else "\n"
    )
    return (
        f"% !!! GENERATED by tools/make_tables.py from {source}. Do not edit by hand. !!!\n"
        f"% Regenerate:  uv run python tools/make_tables.py\n"
        f"\\begin{{{env}}}[t]\n"
        f"  \\centering\n"
        f"  \\caption{{{caption}}}\n"
        f"  \\label{{{label}}}\n"
        f"  \\small\n"
        f"  \\begin{{tabular}}{{{colspec}}}\n"
        f"    \\toprule\n"
        f"{body}"
        f"    \\bottomrule\n"
        f"  \\end{{tabular}}{note_tex}"
        f"\\end{{{env}}}\n"
    )


# ---------------------------------------------------------------------------------------
# T1. Inequality: the equalization result. The paper's centrepiece table.
# ---------------------------------------------------------------------------------------
def t_inequality() -> str:
    d = load_json("inequality_stats")["measures"]
    rows = [
        ("R_i", r"$R_i$ (residential)", "Where you live"),
        ("A_drive", r"$A_i^{\text{drive}}$", "Where you go (drive)"),
        ("A_modal", r"$A_i^{\text{modal}}$", "Where you go (observed modes)"),
        ("A_mnl", r"$A_i^{\text{MNL}}$", "Where you go (modeled modes)"),
        ("E_i", r"$E_i$ (composite day)", "Time-weighted day"),
    ]
    body = (
        "    Measure & Interpretation & Mean & Gini & Top 10\\% & P90/P10 \\\\\n"
        "    \\midrule\n"
    )
    for key, tex, interp in rows:
        if key not in d:
            continue
        m = d[key]
        p90, p10 = m["p90"], m["p10"]
        ratio = p90 / p10 if p10 > 0 else float("nan")
        body += (
            f"    {tex} & {interp} & {m['mean_popwtd']:.1f} & {m['gini_popwtd']:.3f} & "
            f"{100 * m['top_decile_share_popwtd']:.1f}\\% & {ratio:.2f}$\\times$ \\\\\n"
        )
    note = (
        "All statistics are population-weighted, so each is a statement about people rather than about "
        "block groups. ``Top 10\\%'' is the share of total exposure borne by the decile of the population "
        "with the highest exposure; 10\\% would indicate perfect equality. P90/P10 is the ratio of the "
        "90th to the 10th population-weighted percentile."
    )
    # The caption states the two headline ratios, so it is computed, not typed: a hand-written
    # "roughly eight times" silently becomes wrong the first time the pipeline is re-baked.
    r_ri = d["R_i"]["p90"] / d["R_i"]["p10"]
    r_am = d["A_mnl"]["p90"] / d["A_mnl"]["p10"]
    return wrap(
        body,
        caption=(
            "Exposure inequality collapses when exposure is measured over a trajectory rather than at a "
            f"residence. A New Yorker at the 90th percentile of residential exposure lives under "
            f"{r_ri:.1f} times the cameras of one at the 10th percentile, but moves through only "
            f"{r_am:.2f} times as many."
        ),
        label="tab:inequality",
        colspec="llrrrr",
        note=note,
        source="data/derived/results/inequality_stats.json",
    )


# ---------------------------------------------------------------------------------------
# T2. The control ladder: what the disorder narrative can rationalize.
# ---------------------------------------------------------------------------------------
def t_ladder() -> str:
    d = load_json("crime_ladder")
    lad = d["ladders"]["R_i"]
    med = d["mediator_racialization"]
    rungs = [
        ("rung1_total", "(1) No controls"),
        ("rung2_landuse", "(2) + Land use"),
        ("rung3_crime", "(3) + Crime"),
        ("rung4_crime_311", "(4) + Crime + 311"),
    ]
    body = "    Specification & " + " & ".join(t for _, t in FOCALS) + " \\\\\n    \\midrule\n"
    for key, label in rungs:
        cells = []
        for f, _ in FOCALS:
            if f not in lad:
                cells.append("--")
                continue
            b, s = lad[f][key]
            cells.append(f"{signed(b)} ({se(s)})")
        body += f"    {label} & " + " & ".join(cells) + " \\\\\n"
    body += "    \\midrule\n    \\multicolumn{5}{l}{\\emph{The mediators are themselves racialized:}} \\\\\n"
    keymap = {"%Hisp": "pct_hisp", "%Black": "pct_black", "%White": "pct_white", "income": "income"}
    for mk, mlabel in [("log1p(crime)", "Crime density"), ("log1p(311)", "311 disorder density")]:
        cells = []
        for f, _ in FOCALS:
            b, s, _n = med[mk][keymap[f]]
            cells.append(f"{signed(b)} ({se(s)})")
        body += f"    \\quad {mlabel} & " + " & ".join(cells) + " \\\\\n"
    n_dem = lad["%Hisp"]["n"]
    n_inc = lad["income"]["n"]
    note = (
        f"Population-weighted WLS with HC1-robust standard errors (in parentheses). Each column is a "
        f"separate ladder for that focal covariate: specification (1) is the bivariate association, and "
        f"the controls are added to that column's regression alone, so the mediation denominators stay "
        f"well-defined. Coefficients are cameras per standard deviation of the focal covariate. "
        f"$N={n_dem:,}$ for the demographic "
        f"specifications and $N={n_inc:,}$ for income, which the ACS suppresses in roughly 1,040 small "
        f"block groups. The lower panel regresses each mediator on the same focal covariates: both crime "
        f"and 311 complaint density are strongly patterned by ethnicity, so conditioning on them removes "
        f"variation that is itself a product of the disparity under study. We therefore report "
        f"specification (1) as the estimate of interest and the remainder as a decomposition of what the "
        f"disorder rationale can account for, not as a set of confounders to be removed."
    )
    return wrap(
        body,
        caption=(
            "Residential exposure $R_i$ against demographics, adding controls. Conditioning on crime and "
            "311 complaint density absorbs most of the ethnic disparity, but both mediators are themselves "
            "predicted by ethnicity."
        ),
        label="tab:ladder",
        colspec="lrrrr",
        note=note,
        source="data/derived/results/crime_ladder.json",
    )


# ---------------------------------------------------------------------------------------
# T3. Need-neutral counterfactual. Specification-free: no regression, no controls.
# ---------------------------------------------------------------------------------------
def t_counterfactual() -> str:
    d = load_json("counterfactual")
    blocks = d["blocks"]
    race = blocks["Excess exposure by plurality race/ethnicity"]
    inc = blocks["Excess exposure by income quintile"]

    # Exact keys, never fuzzy-matched. `excess_*` is an absolute camera count and `pct_excess_*`
    # is already in percent; an earlier version guessed between them and printed "+714%".
    # A table generator that can silently pick the wrong field is how a wrong number reaches print.
    NEED = ("R_actual", "R_neutral_pop", "pct_excess_pop", "R_neutral_ambient", "pct_excess_ambient")

    def cells(g: dict) -> str:
        missing = [k for k in NEED if k not in g]
        if missing:
            sys.exit(f"counterfactual.json: missing {missing}; have {sorted(g)}")
        return (
            f"{g['R_actual']:.1f} & {g['R_neutral_pop']:.1f} & ${g['pct_excess_pop']:+.1f}\\%$ & "
            f"{g['R_neutral_ambient']:.1f} & ${g['pct_excess_ambient']:+.1f}\\%$"
        )

    body = (
        "    & Observed & \\multicolumn{2}{c}{Need $\\propto$ population} & "
        "\\multicolumn{2}{c}{Need $\\propto$ ambient} \\\\\n"
        "    \\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
        "    Group & $R_i$ & Neutral & Excess & Neutral & Excess \\\\\n"
        "    \\midrule\n"
    )
    for name, g in race.items():
        label = name.split(" (")[0].replace("%", r"\%")
        n = name.split("n=")[1].rstrip(")") if "n=" in name else ""
        body += f"    {label} ($n={n}$) & {cells(g)} \\\\\n"
    body += "    \\midrule\n"
    for name, g in inc.items():
        q = name.split(" (")[0]
        body += f"    Income {q} & {cells(g)} \\\\\n"
    note = (
        "Surveillance intensity is reallocated in proportion to need over the same walksheds, normalized "
        "so that total population-weighted exposure is conserved, and each block group's counterfactual "
        "exposure $R_i^{\\text{neutral}}$ is evaluated on its own walkshed. ``Excess'' is "
        "$100(R_i / R_i^{\\text{neutral}} - 1)$, "
        "population-weighted within each group. Need proportional to ``population'' takes residents alone; "
        "need proportional to ``ambient'' takes residents plus inbound workers, which is the better proxy "
        "for who is actually on the street during the day. The two proxies bracket the estimate: the sign "
        "is stable across both, the magnitude is not. The normalization conserves total population-weighted "
        "exposure, so the mean excess is exactly zero by design. Income quintiles hold a fifth of the "
        "population of income-reporting block groups each, the same construction as "
        "Table~\\ref{tab:quintiles}. This quantity involves no regression "
        "and no covariate selection, and so cannot be attacked on specification grounds."
    )
    return wrap(
        body,
        caption=(
            "Observed exposure against a need-neutral allocation of the same camera stock. Black-plurality "
            "and Hispanic-plurality block groups carry more exposure than need alone predicts; "
            "White-plurality and high-income block groups carry less."
        ),
        label="tab:counterfactual",
        colspec="lrrrrr",
        note=note,
        source="data/derived/results/counterfactual.json",
    )


# ---------------------------------------------------------------------------------------
# T4. Disparity across measures: the equalization, in coefficients.
# ---------------------------------------------------------------------------------------
def t_disparity_by_measure() -> str:
    d = load_json("crime_ladder")["ladders"]
    order = [("R_i", r"$R_i$ (residential)"), ("E_i", r"$E_i$ (composite day)"), ("A_mnl", r"$A_i^{\text{MNL}}$ (activity space)")]
    body = "    Outcome & " + " & ".join(t for _, t in FOCALS) + " \\\\\n    \\midrule\n"
    for key, tex in order:
        if key not in d:
            continue
        cells = []
        for f, _ in FOCALS:
            b, s = d[key][f]["rung1_total"]
            cells.append(f"{signed(b)} ({se(s)})")
        body += f"    {tex} & " + " & ".join(cells) + " \\\\\n"
    note = (
        "Population-weighted WLS, no controls, HC1-robust standard errors; each cell is a separate "
        "bivariate regression of the row's outcome on the column's covariate. Coefficients are cameras per "
        "standard deviation of the focal covariate, so they are comparable in units across rows but not in "
        "relative terms, because the outcomes have different dispersions. The ethnic gradient that is sharp "
        "in residential exposure is close to zero in activity-space exposure."
    )
    return wrap(
        body,
        caption=(
            "The residential disparity does not survive the commute. The same regression, run against "
            "residence-based, composite, and activity-space exposure."
        ),
        label="tab:disparity-by-measure",
        colspec="lrrrr",
        note=note,
        source="data/derived/results/crime_ladder.json",
    )


# ---------------------------------------------------------------------------------------
# T5. Occlusion: a characterized null. The reviewer-objection table.
# ---------------------------------------------------------------------------------------
def t_occlusion() -> str:
    d = load_json("occlusion")
    body = (
        "    Assumed range & \\multicolumn{2}{c}{Sightlines removed} & Cameras removed \\\\\n"
        "    \\cmidrule(lr){2-3}\n"
        "    (CCTV / DOT) & Point-level & Path-level & from $R_i$ \\\\\n"
        "    \\midrule\n"
    )
    for r in d["range_sensitivity"]:
        star = r"\;$\star$" if r["range_scale"] == 1 else ""
        body += (
            f"    {r['cctv_range_m']}\\,m / {r['dot_range_m']}\\,m{star} & "
            f"{100 * r['point_level_attenuation']:.2f}\\% & "
            f"{100 * r['path_level_attenuation']:.2f}\\% & "
            f"{r['cameras_killed']:,} \\\\\n"
        )
    h = d["headline"]
    top_point = 100 * d["range_sensitivity"][-1]["point_level_attenuation"]
    note = (
        f"$\\star$ marks the modeled range used throughout the paper. Line of sight is tested against "
        f"{h['walls']:,} building-facade segments from {h['footprints']:,} footprints. ``Point-level'' is the "
        f"fraction of (camera, street-point) sightlines a building blocks; ``path-level'' is the fraction of "
        f"distinct cameras thereby removed from $R_i$. The two differ because a camera is removed only if "
        f"every one of its sightlines into the walkshed is blocked: at the modeled range "
        f"{100 * h['cameras_saved_by_another_sightline'] / (h['cameras_saved_by_another_sightline'] + h['cameras_fully_occluded']):.0f}\\% "
        f"of the cameras occlusion touches at all are blocked at one point on the walk yet still see the "
        f"walker at another. The bottom row is a positive control: the same code, index, and host-building "
        f"logic, with only the range multiplied, removes {top_point:.0f}\\% of all sightlines."
    )
    return wrap(
        body,
        caption=(
            f"Building occlusion, swept over the assumed camera range. At the modeled range it removes "
            f"{100 * h['path_level_attenuation']:.2f}\\% of $R_i$; the effect only becomes material past "
            f"roughly 60\\,m, when a camera's reach leaves the street canyon."
        ),
        label="tab:occlusion",
        wide=False,
        colspec="lrrr",
        note=note,
        source="data/derived/results/occlusion.json",
    )


# ---------------------------------------------------------------------------------------
# T6. Undercount. The correction is a robustness result, not an amplification result.
# ---------------------------------------------------------------------------------------
def t_recall() -> str:
    cr = load_json("capture_recapture")
    g, b = cr["global"], cr["bootstrap_95"]
    dis = cr["disparity_under_correction"]
    body = (
        "    \\multicolumn{4}{l}{\\emph{(a) Two-source estimate of the camera census}} \\\\\n"
        "    \\midrule\n"
        f"    Observed (merged census) & \\multicolumn{{3}}{{r}}{{{g['observed']:,.0f}}} \\\\\n"
        f"    Chapman $\\hat{{N}}$ & \\multicolumn{{3}}{{r}}{{{g['N']:,.0f}}} "
        f"[{b['N_lo']:,.0f}, {b['N_hi']:,.0f}] \\\\\n"
        f"    Implied recall $r$ & \\multicolumn{{3}}{{r}}{{{g['recall']:.3f}}} "
        f"[{b['recall_lo']:.3f}, {b['recall_hi']:.3f}] \\\\\n"
        "    \\midrule\n"
        "    \\multicolumn{4}{l}{\\emph{(b) Effect of correcting for it}} \\\\\n"
        "    \\midrule\n"
        "    & Mean $R_i$ & $\\rho$(\\%Hisp) & $\\rho$(income) \\\\\n"
        "    \\midrule\n"
    )
    for key, label in [("raw", "Observed counts"), ("global", "Uniform recall"), ("spatial", "Borough-varying recall")]:
        if key not in dis:
            continue
        m = dis[key]
        body += (
            f"    {label} & {m['mean_R']:.1f} & {signed(m['corr_hispanic'], 3)} & "
            f"{signed(m['corr_income'], 3)} \\\\\n"
        )
    note = (
        "Panel (a): Chapman two-source estimator over the Amnesty crowdsourced census and the Dahir et al.\\ "
        "detector census; brackets are bootstrap 95\\% intervals. Panel (b): the correction inflates only "
        "camera groups no surveyed source attests, so exposure rescales by roughly $1/r \\approx 1.9$ and "
        "any coefficient in cameras per standard deviation inflates with it. We therefore report the "
        "scale-free correlations. The focal \\%Hispanic correlation barely moves; the income correlation "
        "moves somewhat more because the surveyed layers that confirm a group are Manhattan-concentrated, "
        "so the correction inflates the outer boroughs relatively more (the enforcement-layer disclosure "
        "in the robustness discussion is the same fact). The correction changes the units of the disparity, "
        "not its magnitude. Both censuses derive from Google Street View, so their overlap is positively "
        "dependent and $\\hat{N}$ is, if anything, an underestimate of the true count."
    )
    return wrap(
        body,
        caption=(
            "Camera-census undercount and its effect on the disparity. Correcting for an estimated 50\\% "
            "recall rescales exposure but leaves the relative disparity essentially unchanged."
        ),
        label="tab:recall",
        wide=False,
        colspec="lrrr",
        note=note,
        source="data/derived/results/capture_recapture.json",
    )


# ---------------------------------------------------------------------------------------
# T7. Borough descriptives, straight off the exposure table.
# ---------------------------------------------------------------------------------------
BORO = {"36061": "Manhattan", "36047": "Brooklyn", "36081": "Queens", "36005": "Bronx", "36085": "Staten Island"}


def _table() -> pd.DataFrame:
    """The joined per-block-group table, with the columns this module needs coerced to numbers."""
    df = pd.read_csv(EXPOSURE / "exposure_table_nyc.csv", dtype={"GEOID": str})
    for c in ("population", "R_i", "A_drive", "A_modal", "A_mnl", "E_i", "median_hh_income"):
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    return df[df["population"] > 0].copy()


def t_descriptives() -> str:
    df = _table()
    cols = [c for c in ("R_i", "A_mnl", "E_i") if c in df.columns]
    df["boro"] = df["GEOID"].str[:5]

    def wmean(g: pd.DataFrame, c: str) -> float:
        v, w = g[c], g["population"]
        m = v.notna()
        return float(np.average(v[m], weights=w[m])) if m.any() else float("nan")

    header = "    Borough & Block groups & Population & " + " & ".join(
        {"R_i": r"$R_i$", "A_mnl": r"$A_i^{\text{MNL}}$", "E_i": r"$E_i$"}[c] for c in cols
    )
    body = header + " \\\\\n    \\midrule\n"
    for code, name in BORO.items():
        g = df[df.boro == code]
        if g.empty:
            continue
        cells = " & ".join(f"{wmean(g, c):.1f}" for c in cols)
        body += f"    {name} & {len(g):,} & {g['population'].sum() / 1e6:.2f}M & {cells} \\\\\n"
    body += "    \\midrule\n"
    cells = " & ".join(f"{wmean(df, c):.1f}" for c in cols)
    body += f"    \\textbf{{Citywide}} & {len(df):,} & {df['population'].sum() / 1e6:.2f}M & {cells} \\\\\n"
    n_zero = int((df["R_i"] == 0).sum())
    pop_zero = int(df.loc[df["R_i"] == 0, "population"].sum())
    note = (
        "Population-weighted mean distinct cameras. $R_i$ counts cameras whose field of view covers any "
        "street point reachable in a 10-minute walk of the block-group centroid. $A_i^{\\text{MNL}}$ adds "
        "the commute and the destination walkshed under a mode-choice model. $E_i$ is the time-weighted "
        f"composite day. {n_zero} block groups ({pop_zero:,} residents) have zero cameras within a "
        "ten-minute walk; they are real zeros and enter every statistic. Staten Island shows the largest "
        "gap between residence and activity space."
    )
    return wrap(
        body,
        caption="Sample and exposure by borough.",
        label="tab:descriptives",
        colspec="lrr" + "r" * len(cols),
        note=note,
        source="data/derived/exposure/exposure_table_nyc.csv",
    )


# ---------------------------------------------------------------------------------------
# T8. Income quintiles: the equalization, seen as a gradient that flattens.
# ---------------------------------------------------------------------------------------
def t_quintiles() -> str:
    df = _table()
    df = df[df["median_hh_income"].notna()].copy()

    # Population-weighted quintiles: cut on the CDF of people, not of block groups, so each
    # bin holds a fifth of New Yorkers rather than a fifth of polygons.
    df = df.sort_values("median_hh_income")
    cw = df["population"].cumsum() / df["population"].sum()
    df["q"] = np.minimum((cw * 5).astype(int) + 1, 5)

    cols = [c for c in ("R_i", "A_mnl", "E_i") if c in df.columns]
    tex = {"R_i": r"$R_i$", "A_mnl": r"$A_i^{\text{MNL}}$", "E_i": r"$E_i$"}
    body = "    Measure & " + " & ".join(f"Q{i}" for i in range(1, 6)) + " & Q1/Q5 \\\\\n    \\midrule\n"
    body += (
        "    Household income & "
        + " & ".join(
            f"\\${np.average(df[df.q == i]['median_hh_income'], weights=df[df.q == i]['population']) / 1000:.0f}k"
            for i in range(1, 6)
        )
        + " & \\\\\n    \\midrule\n"
    )
    for c in cols:
        vals = []
        for i in range(1, 6):
            g = df[df.q == i]
            m = g[c].notna()
            vals.append(float(np.average(g[c][m], weights=g["population"][m])) if m.any() else float("nan"))
        ratio = vals[0] / vals[4] if vals[4] else float("nan")
        body += f"    {tex[c]} & " + " & ".join(f"{v:.1f}" for v in vals) + f" & {ratio:.2f} \\\\\n"
    note = (
        "Quintiles of the population, not of block groups: each column holds a fifth of the New Yorkers "
        "living in block groups that report income. The income row is the population-weighted mean of "
        "block-group median household income within each quintile. Exposure entries are population-weighted "
        "mean distinct cameras. The residential gradient is not monotone, because the highest-income "
        "quintile is concentrated in the dense, heavily surveilled core; the activity-space gradient is "
        "close to flat."
    )
    return wrap(
        body,
        caption="Exposure by income quintile. The residential gradient flattens in activity space.",
        label="tab:quintiles",
        colspec="lrrrrrr",
        note=note,
        source="data/derived/exposure/exposure_table_nyc.csv",
    )


# ---------------------------------------------------------------------------------------
# T9. Network descriptives. Documents the drive/walk split the instrument depends on.
# ---------------------------------------------------------------------------------------
def t_networks() -> str:
    src = RESULTS / "graph_stats.json"
    if not src.exists():
        return ""  # optional; emitted by tools/emit_graph_stats.sh
    d = json.loads(src.read_text())
    classes = ["Street", "Highway", "Ramp", "Bridge", "Tunnel", "Alley", "Path/Trail", "Boardwalk", "Step"]
    body = "    Class & Drive network (km) & Walk network (km) \\\\\n    \\midrule\n"
    for c in classes:
        dv = d["drive"]["km"].get(c)
        wk = d["walk"]["km"].get(c)
        if dv is None and wk is None:
            continue
        body += f"    {c} & {('--' if dv is None else f'{dv:,.0f}')} & {('--' if wk is None else f'{wk:,.0f}')} \\\\\n"
    body += (
        "    \\midrule\n"
        f"    Nodes & {d['drive']['nodes']:,} & {d['walk']['nodes']:,} \\\\\n"
        f"    Edges & {d['drive']['edges']:,} & {d['walk']['edges']:,} \\\\\n"
    )
    note = (
        "Both networks are derived from the NYC Street Centerline (CSCL) file by complementary "
        "classifiers: the drive network excludes segments CSCL flags as non-vehicular "
        "(\\texttt{trafdir=NV}), and the walk network excludes those it flags as non-pedestrian "
        "(\\texttt{nonped=V}). The Brooklyn Bridge illustrates the distinction: its roadway carries "
        "\\texttt{nonped=V} and its promenade \\texttt{trafdir=NV}, so each network retains exactly one. "
        "Every walkshed in this paper is computed on the walk network; commute routes are computed on the "
        "drive network."
    )
    return wrap(
        body,
        caption="The two street networks. Walksheds computed on a drive network would traverse limited-access highway and miss park paths.",
        label="tab:networks",
        wide=False,
        colspec="lrr",
        note=note,
        source="data/derived/results/graph_stats.json",
    )


# ---------------------------------------------------------------------------------------
# T10. Spatial specification + MAUP. Appendix: the "your standard errors are wrong" table.
# ---------------------------------------------------------------------------------------
def t_spatial() -> str:
    src = RESULTS / "spatial_econometrics.json"
    if not src.exists():
        return ""  # emitted by tools/spatial_econometrics.py
    d = json.loads(src.read_text())
    R = d["outcomes"].get("R_i")
    if not R:
        return ""
    focals = [("%Hisp", r"\%Hispanic"), ("%Black", r"\%Black"), ("income", "Median income")]

    body = "    \\multicolumn{4}{l}{\\emph{(a) Model selection (outcome $R_i$)}} \\\\\n    \\midrule\n"
    body += f"    Moran's $I$ of residuals & \\multicolumn{{3}}{{r}}{{{signed(R['moran_i'], 3)} ($p<0.001$)}} \\\\\n"
    aics = R["aic"]
    body += "    AIC & \\multicolumn{3}{r}{" + ", ".join(f"{m} {v:.0f}" for m, v in aics.items()) + "} \\\\\n"
    body += f"    Selected & \\multicolumn{{3}}{{r}}{{{R['selected']}}} \\\\\n"

    body += "    \\midrule\n    \\multicolumn{4}{l}{\\emph{(b) Estimates, cameras per SD}} \\\\\n    \\midrule\n"
    body += "    & " + " & ".join(t for _, t in focals) + " \\\\\n"
    conley = R["ols_conley"]
    body += (
        "    OLS, Conley HAC SE & "
        + " & ".join(f"{signed(conley[k][0])} ({se(conley[k][1])})" for k, _ in focals)
        + " \\\\\n"
    )
    imp = R.get("impacts", {})
    if imp:
        for model, lbl in [("sdem", "SDEM total impact"), ("sdm", "SDM total impact")]:
            body += (
                f"    {lbl} & "
                + " & ".join(signed(imp[k][model][2]) if k in imp else "--" for k, _ in focals)
                + " \\\\\n"
            )

    maup = d.get("maup", {})
    if maup:
        body += "    \\midrule\n    \\multicolumn{4}{l}{\\emph{(c) MAUP: same specification, coarser zonings}} \\\\\n    \\midrule\n"
        keymap = {"%Hisp": "pct_hisp", "%Black": "pct_black", "income": "income"}
        for lbl, m in maup.items():
            body += (
                f"    {lbl} ($n={m['n']:,}$) & "
                + " & ".join(signed(m[keymap[k]]) for k, _ in focals)
                + " \\\\\n"
            )

    note = (
        "Panel (a): $R_i$ is strongly spatially autocorrelated, so OLS standard errors are not "
        "trustworthy. We fit the full ladder (OLS, spatial lag, spatial error, and both Durbin "
        "variants) and select on AIC. Panel (b): the Conley HAC row uses a triangular kernel with a "
        "2\\,km bandwidth, which requires no model of the spatial process; the impact rows are the "
        "LeSage--Pace decomposition, in which the total impact includes the effect of a block group's "
        "neighbors on itself. The spatial-lag models attribute much of the effect to the lag term "
        "($\\rho$ near 0.9), which inflates the implied total; we report both and rely on the "
        "AIC-selected error specification. Panel (c): re-estimating after aggregating upward gives "
        "coefficients close to the block-group estimate, so the disparity is not an artifact of the "
        "zoning we happened to choose."
    )
    return wrap(
        body,
        caption=(
            "Spatial specification and scale. The disparity survives spatial inference and is stable "
            "across aggregation scales."
        ),
        label="tab:spatial",
        colspec="lrrr",
        note=note,
        source="data/derived/results/spatial_econometrics.json",
    )


# ---------------------------------------------------------------------------------------
# Macros. Every number that appears in the *prose* is defined here, so the body text is as
# reproducible as the tables. A statistic quoted inline and not defined here is a statistic
# that will silently go stale on the next re-bake.
# ---------------------------------------------------------------------------------------
def t_macros() -> str:
    ineq = load_json("inequality_stats")["measures"]
    lad = load_json("crime_ladder")
    cr = load_json("capture_recapture")
    occ = load_json("occlusion")
    cf = load_json("counterfactual")
    ne = load_json("network_effect")
    det = load_json("detection_model")["detection_model"]
    sw = load_json("subway_sweep")
    pm = load_json("population_mixed")
    spa = load_json("spatial_econometrics")["outcomes"]["R_i"]["ols_conley"]
    df = _table()

    R, A = ineq["R_i"], ineq["A_mnl"]
    ri_ratio = R["p90"] / R["p10"]
    am_ratio = A["p90"] / A["p10"]
    Rlad, Alad = lad["ladders"]["R_i"], lad["ladders"]["A_mnl"]
    med = lad["mediator_racialization"]
    g, bs = cr["global"], cr["bootstrap_95"]
    dis = cr["disparity_under_correction"]
    oh = occ["headline"]
    race = cf["blocks"]["Excess exposure by plurality race/ethnicity"]

    def grp(prefix: str) -> dict:
        return next(v for k, v in race.items() if k.startswith(prefix))

    m: dict[str, str] = {
        # sample
        "NBg": f"{len(df):,}",
        "NPop": f"{df['population'].sum() / 1e6:.2f}",
        "NCameraGroups": f"{oh['camera_groups']:,}",
        "NSensors": f"{oh['sensors_total']:,}",
        # levels
        "RiMean": f"{R['mean_popwtd']:.1f}",
        "AmnlMean": f"{A['mean_popwtd']:.1f}",
        "MobilityFactor": f"{A['mean_popwtd'] / R['mean_popwtd']:.1f}",
        # inequality
        "RiGini": f"{R['gini_popwtd']:.3f}",
        "AmnlGini": f"{A['gini_popwtd']:.3f}",
        "GiniDrop": f"{100 * (1 - A['gini_popwtd'] / R['gini_popwtd']):.0f}",
        "RiTopDecile": f"{100 * R['top_decile_share_popwtd']:.1f}",
        "AmnlTopDecile": f"{100 * A['top_decile_share_popwtd']:.1f}",
        "RiPRatio": f"{ri_ratio:.1f}",
        "AmnlPRatio": f"{am_ratio:.2f}",
        # disparity
        "HispRi": signed(Rlad["%Hisp"]["rung1_total"][0]),
        "HispRiSE": se(Rlad["%Hisp"]["rung1_total"][1]),
        "HispRiControlled": signed(Rlad["%Hisp"]["rung4_crime_311"][0]),
        "HispRiControlledSE": se(Rlad["%Hisp"]["rung4_crime_311"][1]),
        "HispAmnl": signed(Alad["%Hisp"]["rung1_total"][0]),
        "HispAmnlSE": se(Alad["%Hisp"]["rung1_total"][1]),
        "WhiteAmnl": signed(Alad["%White"]["rung1_total"][0]),
        "IncomeAmnl": signed(Alad["income"]["rung1_total"][0]),
        "HispEi": signed(lad["ladders"]["E_i"]["%Hisp"]["rung1_total"][0]),
        "BlackRi": signed(Rlad["%Black"]["rung1_total"][0]),
        "BlackRiLandUse": signed(Rlad["%Black"]["rung2_landuse"][0]),
        "WhiteRi": signed(Rlad["%White"]["rung1_total"][0]),
        "IncomeRi": signed(Rlad["income"]["rung1_total"][0]),
        "HispPctViaCrime": f"{Rlad['%Hisp']['pct_via_crime_311']:.0f}",
        # mediators
        "CrimeOnHisp": signed(med["log1p(crime)"]["pct_hisp"][0]),
        "CrimeOnWhite": signed(med["log1p(crime)"]["pct_white"][0]),
        "DisorderOnHisp": signed(med["log1p(311)"]["pct_hisp"][0]),
        # counterfactual
        "BlackExcessPop": f"{grp('Black')['pct_excess_pop']:.1f}",
        "BlackExcessAmb": f"{grp('Black')['pct_excess_ambient']:.1f}",
        "HispExcessPop": f"{grp('Hispanic')['pct_excess_pop']:.1f}",
        "HispExcessAmb": f"{grp('Hispanic')['pct_excess_ambient']:.1f}",
        "WhiteExcessPop": f"{abs(grp('White')['pct_excess_pop']):.1f}",
        "WhiteExcessAmb": f"{abs(grp('White')['pct_excess_ambient']):.1f}",
        # undercount
        "CensusObserved": f"{g['observed']:,.0f}",
        "CensusEstimated": f"{g['N']:,.0f}",
        "CensusRecall": f"{g['recall']:.3f}",
        "CensusRecallLo": f"{bs['recall_lo']:.3f}",
        "CensusRecallHi": f"{bs['recall_hi']:.3f}",
        "CorrHispRaw": signed(dis["raw"]["corr_hispanic"], 3),
        "CorrHispCorrected": signed(dis["global"]["corr_hispanic"], 3),
        "RecallRescale": f"{dis['global']['mean_R'] / dis['raw']['mean_R']:.2f}",
        # occlusion (two decimals: at the modeled range the attenuation is hundredths of a
        # percent, and one-decimal rounding overstated 0.04% as "0.1%")
        "OcclWalls": f"{oh['walls'] / 1e6:.2f}",
        "OcclFootprints": f"{oh['footprints'] / 1e6:.2f}",
        "OcclPoint": f"{100 * oh['point_level_attenuation']:.2f}",
        "OcclPath": f"{100 * oh['path_level_attenuation']:.2f}",
        "OcclSavedPct": f"{100 * oh['cameras_saved_by_another_sightline'] / (oh['cameras_saved_by_another_sightline'] + oh['cameras_fully_occluded']):.0f}",
        # the positive-control arm (largest range multiple): point-level sightlines removed
        "OcclTopPoint": f"{100 * occ['range_sensitivity'][-1]['point_level_attenuation']:.0f}",
        # population-honest lived exposure (population_mixed.json): the C4 scope check.
        # A_lived mixes commuters (A_mnl day) and non-commuters incl. WFH (R_i day).
        "CommuterShare": f"{100 * pm['commuter_share_popwtd']:.0f}",
        "LivedGini": f"{pm['gini']['A_lived']:.3f}",
        "LivedGiniDrop": f"{pm['gini_drop_lived_pct']:.0f}",
        "LivedHispCorr": signed(pm['corr_popwtd']['A_lived']['pct_hispanic'], 3),
        "LivedIncomeCorr": signed(pm['corr_popwtd']['A_lived']['income'], 3),
        # walk-vs-drive network correction (network_effect.json; replaces the two numbers that
        # were typed into the networks paragraph by hand and went stale)
        "NetRiDeltaPct": f"{ne['delta']['mean_pct']:.1f}",
        "NetHispDrive": signed(ne["drive"]["hisp_rung1"][0]),
        "NetHispDelta": signed(ne["delta"]["hisp"]),
        # spatial inference (joint demographic spec, NO crime controls -- app:spatial)
        "HispConley": signed(spa["%Hisp"][0]),
        "HispConleySE": se(spa["%Hisp"][1]),
        # detection model: is the undercount non-differential? (detection_model.json)
        "DetectN": f"{det['n_detections']:,}",
        "DetectPHisp": f"{det['terms']['hisp']['p']:.2f}",
        "DetectPBlack": f"{det['terms']['black']['p']:.2f}",
        "DetectPIncome": f"{det['terms']['inc']['p']:.2f}",
        "BoroughRecallLo": f"{100 * min(cr['borough_recall'].values()):.1f}",
        "BoroughRecallHi": f"{100 * max(cr['borough_recall'].values()):.1f}",
        # subway-camera sensitivity (subway_sweep.json)
        "SubwayFlipHisp": f"{sw['flips']['%Hisp']:.1f}",
        "SubwayCentralCams": f"{sw['central_effective_cams_per_trip']:.0f}",
        # raw pop-weighted correlations (scale-free anchors for the prose)
        "BlackCorr": signed(dis["raw"]["corr_black"], 2),
        "CorrIncRaw": signed(dis["raw"]["corr_income"], 3),
        "CorrIncCorrected": signed(dis["global"]["corr_income"], 3),
        # zero-exposure block groups (real zeros, kept in every statistic)
        "RiZeroBGs": f"{int((df['R_i'] == 0).sum())}",
        "RiZeroPop": f"{int(df.loc[df['R_i'] == 0, 'population'].sum()):,}",
    }
    out = [
        "% !!! GENERATED by tools/make_tables.py. Do not edit by hand. !!!",
        "% Every statistic quoted in the prose is defined here, so the body text cannot go stale.",
    ]
    out += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]
    return "\n".join(out) + "\n"


TABLES_TO_WRITE = {
    "macros": t_macros,
    "descriptives": t_descriptives,
    "inequality": t_inequality,
    "quintiles": t_quintiles,
    "ladder": t_ladder,
    "counterfactual": t_counterfactual,
    "disparity_by_measure": t_disparity_by_measure,
    "recall": t_recall,
    "occlusion": t_occlusion,
    "networks": t_networks,
    "spatial": t_spatial,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any table on disk differs")
    args = ap.parse_args()

    TABLES.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, fn in TABLES_TO_WRITE.items():
        tex = fn()
        if not tex:
            continue
        path = TABLES / f"{name}.tex"
        if args.check:
            if not path.exists() or path.read_text() != tex:
                stale.append(name)
        else:
            path.write_text(tex)
            print(f"  wrote {path.relative_to(ROOT)}")

    if args.check:
        if stale:
            print(f"STALE (re-run tools/make_tables.py): {', '.join(stale)}", file=sys.stderr)
            return 1
        print("all tables up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
